// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/1/2025, 5:42:09 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/lordrag/github/linktree/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/lordrag/github/linktree/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/lordrag/github/linktree/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/lordrag/github/linktree/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/lordrag/github/linktree/plugins/**/*.{js,ts,mjs}","/home/lordrag/github/linktree/composables/**/*.{js,ts,mjs}","/home/lordrag/github/linktree/utils/**/*.{js,ts,mjs}","/home/lordrag/github/linktree/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/lordrag/github/linktree/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/lordrag/github/linktree/app.config.{js,ts,mjs}","/home/lordrag/github/linktree/app/spa-loading-template.html"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;