name: Deploy Nuxt 3 to GitHub Pages

on:
  push:
    branches:
      - main  # Quand tu pushes sur main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # ou la version que tu utilises

      - name: Install dependencies
        run: npm install

      - name: Generate static site
        run: npx nuxi generate

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: .output/public
          publish_branch: gh-pages
